version: '3'
services:
  vehicle_emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    container_name: vehicle_emulator
    network_mode: "host"  # Use host network for CAN socket access
