# Dockerfile for gif_display
FROM python:3.9-slim
RUN apt-get update && apt-get install -y libsdl1.2-dev && rm -rf /var/lib/apt/lists/*
RUN pip install pygame python-can
WORKDIR /app
COPY ./ /app
CMD ["python", "main.py"]
